(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["index"],{

/***/ "./src/routes/index.svelte":
/*!*********************************!*\
  !*** ./src/routes/index.svelte ***!
  \*********************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* harmony import */ var svelte__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! svelte */ "./node_modules/svelte/index.mjs");
/* src/routes/index.svelte generated by Svelte v3.31.0 */


const { console: console_1 } = svelte_internal__WEBPACK_IMPORTED_MODULE_0__["globals"];

const file = "src/routes/index.svelte";

function create_fragment(ctx) {
	let t0;
	let svg;
	let text0;
	let t1;
	let line;
	let text1;
	let t2;
	let text2;
	let t3;
	let text3;
	let t4;
	let text4;
	let t5;
	let text5;
	let t6;
	let text6;
	let t7;
	let text7;
	let t8;
	let text8;
	let t9;
	let text9;
	let t10;
	let text10;
	let t11;
	let text11;
	let t12;
	let text12;
	let t13;
	let text13;
	let t14;
	let text14;
	let t15;
	let text15;
	let t16;
	let text16;
	let t17;
	let text17;
	let t18;
	let text18;
	let t19;
	let text19;
	let t20;
	let text20;
	let t21;
	let text21;
	let t22;
	let text22;
	let t23;
	let text23;
	let t24;
	let text24;
	let t25;
	let text25;
	let t26;
	let text26;
	let t27;
	let text27;
	let t28;
	let t29;
	let mounted;
	let dispose;

	const block = {
		c: function create() {
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			svg = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("svg");
			text0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("text");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("SecCams");
			line = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("line");
			text1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("text");
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("PC1 Motion");
			text2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("text");
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(/*pc1LastMovingDate*/ ctx[4]);
			text3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("text");
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(/*pc1LastMovingTime*/ ctx[5]);
			text4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("text");
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("1 Last Still");
			text5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("text");
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(/*pc1LastStillDate*/ ctx[6]);
			text6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("text");
			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(/*pc1LastStillTime*/ ctx[7]);
			text7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("text");
			t8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("1 Ping status");
			text8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("text");
			t9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(/*pc1status*/ ctx[10]);
			text9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("text");
			t10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("2 Last Motion");
			text10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("text");
			t11 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(/*pc2LastMovingDate*/ ctx[0]);
			text11 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("text");
			t12 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(/*pc2LastMovingTime*/ ctx[1]);
			text12 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("text");
			t13 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("2 Last Still");
			text13 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("text");
			t14 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(/*pc2LastStillDate*/ ctx[2]);
			text14 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("text");
			t15 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(/*pc2LastStillTime*/ ctx[3]);
			text15 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("text");
			t16 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("2 Ping Status");
			text16 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("text");
			t17 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(/*pc2status*/ ctx[11]);
			text17 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("text");
			t18 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Health Check");
			text18 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("text");
			t19 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(/*lhedate*/ ctx[8]);
			text19 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("text");
			t20 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(/*lhetime*/ ctx[15]);
			text20 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("text");
			t21 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("PiCam1 Total");
			text21 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("text");
			t22 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(/*pc1TotalEvents*/ ctx[12]);
			text22 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("text");
			t23 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("PiCam2 Total");
			text23 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("text");
			t24 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(/*pc2TotalEvents*/ ctx[13]);
			text24 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("text");
			t25 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Total Events");
			text25 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("text");
			t26 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(/*totalEvents*/ ctx[14]);
			text26 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("text");
			t27 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Pic Folder Size");
			text27 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("text");
			t28 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(/*picdirsize*/ ctx[9]);
			t29 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("\n\n\n\n\tSorry, your browser does not support inline SVG.");
			this.h();
		},
		l: function claim(nodes) {
			const head_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["query_selector_all"])("[data-svelte=\"svelte-n6u0cb\"]", document.head);
			head_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(nodes);
			svg = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "svg", { viewBox: true }, 1);
			var svg_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(svg);

			text0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(
				svg_nodes,
				"text",
				{
					x: true,
					y: true,
					"font-size": true,
					fill: true
				},
				1
			);

			var text0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(text0);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(text0_nodes, "SecCams");
			text0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);

			line = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(
				svg_nodes,
				"line",
				{
					x1: true,
					y1: true,
					x2: true,
					y2: true,
					style: true
				},
				1
			);

			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(line).forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);

			text1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(
				svg_nodes,
				"text",
				{
					x: true,
					y: true,
					"font-size": true,
					fill: true
				},
				1
			);

			var text1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(text1);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(text1_nodes, "PC1 Motion");
			text1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);

			text2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(
				svg_nodes,
				"text",
				{
					x: true,
					y: true,
					"font-size": true,
					fill: true
				},
				1
			);

			var text2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(text2);
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(text2_nodes, /*pc1LastMovingDate*/ ctx[4]);
			text2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);

			text3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(
				svg_nodes,
				"text",
				{
					x: true,
					y: true,
					"font-size": true,
					fill: true
				},
				1
			);

			var text3_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(text3);
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(text3_nodes, /*pc1LastMovingTime*/ ctx[5]);
			text3_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);

			text4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(
				svg_nodes,
				"text",
				{
					x: true,
					y: true,
					"font-size": true,
					fill: true
				},
				1
			);

			var text4_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(text4);
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(text4_nodes, "1 Last Still");
			text4_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);

			text5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(
				svg_nodes,
				"text",
				{
					x: true,
					y: true,
					"font-size": true,
					fill: true
				},
				1
			);

			var text5_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(text5);
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(text5_nodes, /*pc1LastStillDate*/ ctx[6]);
			text5_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);

			text6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(
				svg_nodes,
				"text",
				{
					x: true,
					y: true,
					"font-size": true,
					fill: true
				},
				1
			);

			var text6_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(text6);
			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(text6_nodes, /*pc1LastStillTime*/ ctx[7]);
			text6_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);

			text7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(
				svg_nodes,
				"text",
				{
					x: true,
					y: true,
					"font-size": true,
					fill: true
				},
				1
			);

			var text7_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(text7);
			t8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(text7_nodes, "1 Ping status");
			text7_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);

			text8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(
				svg_nodes,
				"text",
				{
					x: true,
					y: true,
					"font-size": true,
					fill: true
				},
				1
			);

			var text8_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(text8);
			t9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(text8_nodes, /*pc1status*/ ctx[10]);
			text8_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);

			text9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(
				svg_nodes,
				"text",
				{
					x: true,
					y: true,
					"font-size": true,
					fill: true
				},
				1
			);

			var text9_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(text9);
			t10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(text9_nodes, "2 Last Motion");
			text9_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);

			text10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(
				svg_nodes,
				"text",
				{
					x: true,
					y: true,
					"font-size": true,
					fill: true
				},
				1
			);

			var text10_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(text10);
			t11 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(text10_nodes, /*pc2LastMovingDate*/ ctx[0]);
			text10_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);

			text11 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(
				svg_nodes,
				"text",
				{
					x: true,
					y: true,
					"font-size": true,
					fill: true
				},
				1
			);

			var text11_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(text11);
			t12 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(text11_nodes, /*pc2LastMovingTime*/ ctx[1]);
			text11_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);

			text12 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(
				svg_nodes,
				"text",
				{
					x: true,
					y: true,
					"font-size": true,
					fill: true
				},
				1
			);

			var text12_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(text12);
			t13 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(text12_nodes, "2 Last Still");
			text12_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);

			text13 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(
				svg_nodes,
				"text",
				{
					x: true,
					y: true,
					"font-size": true,
					fill: true
				},
				1
			);

			var text13_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(text13);
			t14 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(text13_nodes, /*pc2LastStillDate*/ ctx[2]);
			text13_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);

			text14 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(
				svg_nodes,
				"text",
				{
					x: true,
					y: true,
					"font-size": true,
					fill: true
				},
				1
			);

			var text14_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(text14);
			t15 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(text14_nodes, /*pc2LastStillTime*/ ctx[3]);
			text14_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);

			text15 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(
				svg_nodes,
				"text",
				{
					x: true,
					y: true,
					"font-size": true,
					fill: true
				},
				1
			);

			var text15_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(text15);
			t16 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(text15_nodes, "2 Ping Status");
			text15_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);

			text16 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(
				svg_nodes,
				"text",
				{
					x: true,
					y: true,
					"font-size": true,
					fill: true
				},
				1
			);

			var text16_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(text16);
			t17 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(text16_nodes, /*pc2status*/ ctx[11]);
			text16_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);

			text17 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(
				svg_nodes,
				"text",
				{
					x: true,
					y: true,
					"font-size": true,
					fill: true
				},
				1
			);

			var text17_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(text17);
			t18 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(text17_nodes, "Health Check");
			text17_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);

			text18 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(
				svg_nodes,
				"text",
				{
					x: true,
					y: true,
					"font-size": true,
					fill: true
				},
				1
			);

			var text18_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(text18);
			t19 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(text18_nodes, /*lhedate*/ ctx[8]);
			text18_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);

			text19 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(
				svg_nodes,
				"text",
				{
					x: true,
					y: true,
					"font-size": true,
					fill: true
				},
				1
			);

			var text19_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(text19);
			t20 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(text19_nodes, /*lhetime*/ ctx[15]);
			text19_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);

			text20 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(
				svg_nodes,
				"text",
				{
					x: true,
					y: true,
					"font-size": true,
					fill: true
				},
				1
			);

			var text20_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(text20);
			t21 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(text20_nodes, "PiCam1 Total");
			text20_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);

			text21 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(
				svg_nodes,
				"text",
				{
					x: true,
					y: true,
					"font-size": true,
					fill: true
				},
				1
			);

			var text21_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(text21);
			t22 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(text21_nodes, /*pc1TotalEvents*/ ctx[12]);
			text21_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);

			text22 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(
				svg_nodes,
				"text",
				{
					x: true,
					y: true,
					"font-size": true,
					fill: true
				},
				1
			);

			var text22_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(text22);
			t23 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(text22_nodes, "PiCam2 Total");
			text22_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);

			text23 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(
				svg_nodes,
				"text",
				{
					x: true,
					y: true,
					"font-size": true,
					fill: true
				},
				1
			);

			var text23_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(text23);
			t24 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(text23_nodes, /*pc2TotalEvents*/ ctx[13]);
			text23_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);

			text24 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(
				svg_nodes,
				"text",
				{
					x: true,
					y: true,
					"font-size": true,
					fill: true
				},
				1
			);

			var text24_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(text24);
			t25 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(text24_nodes, "Total Events");
			text24_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);

			text25 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(
				svg_nodes,
				"text",
				{
					x: true,
					y: true,
					"font-size": true,
					fill: true
				},
				1
			);

			var text25_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(text25);
			t26 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(text25_nodes, /*totalEvents*/ ctx[14]);
			text25_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);

			text26 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(
				svg_nodes,
				"text",
				{
					x: true,
					y: true,
					"font-size": true,
					fill: true
				},
				1
			);

			var text26_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(text26);
			t27 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(text26_nodes, "Pic Folder Size");
			text26_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);

			text27 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(
				svg_nodes,
				"text",
				{
					x: true,
					y: true,
					"font-size": true,
					fill: true
				},
				1
			);

			var text27_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(text27);
			t28 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(text27_nodes, /*picdirsize*/ ctx[9]);
			text27_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t29 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(svg_nodes, "\n\n\n\n\tSorry, your browser does not support inline SVG.");
			svg_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			document.title = "SecCams";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text0, "x", "0");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text0, "y", "18");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text0, "font-size", "2em");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text0, "fill", "black");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(text0, file, 78, 1, 2131);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(line, "x1", "50");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(line, "y1", "25");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(line, "x2", "260");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(line, "y2", "25");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_style"])(line, "stroke", "rgb(255,0,0)");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_style"])(line, "stroke-width", "2");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(line, file, 80, 1, 2196);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text1, "x", "0");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text1, "y", "47");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text1, "font-size", "1em");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text1, "fill", "black");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(text1, file, 82, 1, 2283);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text2, "x", "135");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text2, "y", "47");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text2, "font-size", "1em");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text2, "fill", "black");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(text2, file, 83, 1, 2351);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text3, "x", "230");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text3, "y", "47");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text3, "font-size", "1em");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text3, "fill", "pink");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(text3, file, 84, 1, 2430);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text4, "x", "0");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text4, "y", "67");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text4, "font-size", "1em");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text4, "fill", "black");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(text4, file, 86, 1, 2508);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text5, "x", "135");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text5, "y", "67");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text5, "font-size", "1em");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text5, "fill", "black");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(text5, file, 87, 1, 2577);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text6, "x", "230");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text6, "y", "67");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text6, "font-size", "1em");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text6, "fill", "blue");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(text6, file, 88, 1, 2655);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text7, "x", "0");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text7, "y", "87");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text7, "font-size", "1em");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text7, "fill", "black");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(text7, file, 90, 1, 2732);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text8, "x", "135");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text8, "y", "87");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text8, "font-size", "1em");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text8, "fill", "blue");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(text8, file, 91, 1, 2835);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text9, "x", "0");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text9, "y", "107");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text9, "font-size", "1em");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text9, "fill", "black");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(text9, file, 93, 1, 2905);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text10, "x", "135");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text10, "y", "107");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text10, "font-size", "1em");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text10, "fill", "black");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(text10, file, 94, 1, 2977);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text11, "x", "230");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text11, "y", "107");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text11, "font-size", "1em");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text11, "fill", "pink");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(text11, file, 95, 1, 3057);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text12, "x", "0");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text12, "y", "127");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text12, "font-size", "1em");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text12, "fill", "black");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(text12, file, 97, 1, 3136);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text13, "x", "135");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text13, "y", "127");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text13, "font-size", "1em");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text13, "fill", "black");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(text13, file, 98, 1, 3206);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text14, "x", "230");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text14, "y", "127");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text14, "font-size", "1em");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text14, "fill", "blue");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(text14, file, 99, 1, 3285);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text15, "x", "0");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text15, "y", "147");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text15, "font-size", "1em");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text15, "fill", "black");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(text15, file, 101, 1, 3363);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text16, "x", "135");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text16, "y", "147");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text16, "font-size", "1em");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text16, "fill", "blue");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(text16, file, 102, 1, 3467);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text17, "x", "0");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text17, "y", "167");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text17, "font-size", "1em");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text17, "fill", "black");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(text17, file, 104, 1, 3539);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text18, "x", "135");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text18, "y", "167");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text18, "font-size", "1em");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text18, "fill", "black");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(text18, file, 105, 1, 3609);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text19, "x", "230");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text19, "y", "167");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text19, "font-size", "1em");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text19, "fill", "red");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(text19, file, 106, 1, 3679);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text20, "x", "0");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text20, "y", "187");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text20, "font-size", "1em");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text20, "fill", "black");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(text20, file, 108, 1, 3747);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text21, "x", "135");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text21, "y", "187");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text21, "font-size", "1em");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text21, "fill", "black");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(text21, file, 109, 1, 3817);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text22, "x", "0");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text22, "y", "207");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text22, "font-size", "1em");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text22, "fill", "black");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(text22, file, 112, 1, 3971);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text23, "x", "135");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text23, "y", "207");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text23, "font-size", "1em");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text23, "fill", "black");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(text23, file, 113, 1, 4041);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text24, "x", "0");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text24, "y", "227");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text24, "font-size", "1em");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text24, "fill", "black");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(text24, file, 116, 1, 4195);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text25, "x", "135");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text25, "y", "227");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text25, "font-size", "1em");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text25, "fill", "black");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(text25, file, 117, 1, 4265);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text26, "x", "0");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text26, "y", "247");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text26, "font-size", "1em");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text26, "fill", "black");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(text26, file, 120, 1, 4416);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text27, "x", "135");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text27, "y", "247");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text27, "font-size", "1em");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(text27, "fill", "black");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(text27, file, 121, 1, 4489);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(svg, "viewBox", "0 -5 300 255");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(svg, file, 77, 0, 2100);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, t0, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, svg, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(svg, text0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(text0, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(svg, line);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(svg, text1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(text1, t2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(svg, text2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(text2, t3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(svg, text3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(text3, t4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(svg, text4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(text4, t5);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(svg, text5);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(text5, t6);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(svg, text6);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(text6, t7);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(svg, text7);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(text7, t8);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(svg, text8);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(text8, t9);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(svg, text9);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(text9, t10);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(svg, text10);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(text10, t11);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(svg, text11);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(text11, t12);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(svg, text12);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(text12, t13);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(svg, text13);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(text13, t14);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(svg, text14);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(text14, t15);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(svg, text15);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(text15, t16);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(svg, text16);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(text16, t17);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(svg, text17);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(text17, t18);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(svg, text18);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(text18, t19);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(svg, text19);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(text19, t20);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(svg, text20);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(text20, t21);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(svg, text21);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(text21, t22);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(svg, text22);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(text22, t23);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(svg, text23);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(text23, t24);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(svg, text24);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(text24, t25);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(svg, text25);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(text25, t26);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(svg, text26);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(text26, t27);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(svg, text27);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(text27, t28);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(svg, t29);

			if (!mounted) {
				dispose = [
					Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["listen_dev"])(text7, "click", /*handlepingPiCam1Click*/ ctx[16], false, false, false),
					Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["listen_dev"])(text15, "click", /*handlepingPiCam2Click*/ ctx[17], false, false, false)
				];

				mounted = true;
			}
		},
		p: function update(ctx, [dirty]) {
			if (dirty & /*pc1LastMovingDate*/ 16) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t3, /*pc1LastMovingDate*/ ctx[4]);
			if (dirty & /*pc1LastMovingTime*/ 32) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t4, /*pc1LastMovingTime*/ ctx[5]);
			if (dirty & /*pc1LastStillDate*/ 64) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t6, /*pc1LastStillDate*/ ctx[6]);
			if (dirty & /*pc1LastStillTime*/ 128) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t7, /*pc1LastStillTime*/ ctx[7]);
			if (dirty & /*pc1status*/ 1024) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t9, /*pc1status*/ ctx[10]);
			if (dirty & /*pc2LastMovingDate*/ 1) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t11, /*pc2LastMovingDate*/ ctx[0]);
			if (dirty & /*pc2LastMovingTime*/ 2) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t12, /*pc2LastMovingTime*/ ctx[1]);
			if (dirty & /*pc2LastStillDate*/ 4) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t14, /*pc2LastStillDate*/ ctx[2]);
			if (dirty & /*pc2LastStillTime*/ 8) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t15, /*pc2LastStillTime*/ ctx[3]);
			if (dirty & /*pc2status*/ 2048) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t17, /*pc2status*/ ctx[11]);
			if (dirty & /*lhedate*/ 256) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t19, /*lhedate*/ ctx[8]);
			if (dirty & /*pc1TotalEvents*/ 4096) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t22, /*pc1TotalEvents*/ ctx[12]);
			if (dirty & /*pc2TotalEvents*/ 8192) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t24, /*pc2TotalEvents*/ ctx[13]);
			if (dirty & /*totalEvents*/ 16384) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t26, /*totalEvents*/ ctx[14]);
			if (dirty & /*picdirsize*/ 512) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t28, /*picdirsize*/ ctx[9]);
		},
		i: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		o: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(t0);
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(svg);
			mounted = false;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["run_all"])(dispose);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_fragment.name,
		type: "component",
		source: "",
		ctx
	});

	return block;
}

function instance($$self, $$props, $$invalidate) {
	let { $$slots: slots = {}, $$scope } = $$props;
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_slots"])("Routes", slots, []);
	let pc2LastMovingDate = "";
	let pc2LastMovingTime = "";
	let pc2LastStillDate = "";
	let pc2LastStillTime = "";
	let pc1LastMovingDate = "";
	let pc1LastMovingTime = "";
	let pc1LastStillDate = "";
	let pc1LastStillTime = "";
	let lhedate = "";
	let lhetime = "";
	let picdirsize = "";
	let pc1status = "";
	let pc2status = "";
	let pc1TotalEvents = "";
	let pc2TotalEvents = "";
	let totalEvents = "";

	Object(svelte__WEBPACK_IMPORTED_MODULE_1__["onMount"])(async () => {
		await fetch(`http://192.168.0.26:8090/stats`, { mode: "cors", method: "GET" }).then(r => r.json()).then(data => {
			console.log(data);

			if (data.health === "None noted") {
				$$invalidate(8, lhedate = "None noted");
			} else {
				$$invalidate(8, lhedate = data.health);
			}

			$$invalidate(9, picdirsize = data.picDirSize);
			$$invalidate(12, pc1TotalEvents = data.picam1AllToday);
			$$invalidate(13, pc2TotalEvents = data.picam2AllToday);
			$$invalidate(14, totalEvents = data.totalEvents);
			$$invalidate(4, pc1LastMovingDate = data.picam1LM["Date"]);
			let ace = data.picam1LM["Time"].split(",");
			$$invalidate(5, pc1LastMovingTime = ace[0]);
			$$invalidate(6, pc1LastStillDate = data.picam1LS["Date"]);
			let kings = data.picam1LS["Time"].split(",");
			$$invalidate(7, pc1LastStillTime = kings[0]);
			$$invalidate(0, pc2LastMovingDate = data.picam2LM["Date"]);
			let queens = data.picam2LM["Time"].split(",");
			$$invalidate(1, pc2LastMovingTime = queens[0]);
			$$invalidate(2, pc2LastStillDate = data.picam2LS["Date"]);
			let jacks = data.picam2LS["Time"].split(",");
			$$invalidate(3, pc2LastStillTime = jacks[0]);
		}).catch(err => console.log(err));
	});

	async function pingPiCam1() {
		await fetch(`http://192.168.0.26:8090/pingpc1`, { mode: "cors", method: "GET" }).then(r => r.json()).then(data => {
			$$invalidate(10, pc1status = data["pc1"]);
		}).catch(err => console.log(err));
	}

	async function pingPiCam2() {
		await fetch(`http://192.168.0.26:8090/pingpc2`, { mode: "cors", method: "GET" }).then(r => r.json()).then(data => {
			$$invalidate(11, pc2status = data["pc2"]);
		}).catch(err => console.log(err));
	}

	let handlepingPiCam1Click = () => {
		let promise = pingPiCam1().catch(err => console.log(err));
	};

	let handlepingPiCam2Click = () => {
		let promise = pingPiCam2().catch(err => console.log(err));
	};

	const writable_props = [];

	Object.keys($$props).forEach(key => {
		if (!~writable_props.indexOf(key) && key.slice(0, 2) !== "$$") console_1.warn(`<Routes> was created with unknown prop '${key}'`);
	});

	$$self.$capture_state = () => ({
		onMount: svelte__WEBPACK_IMPORTED_MODULE_1__["onMount"],
		pc2LastMovingDate,
		pc2LastMovingTime,
		pc2LastStillDate,
		pc2LastStillTime,
		pc1LastMovingDate,
		pc1LastMovingTime,
		pc1LastStillDate,
		pc1LastStillTime,
		lhedate,
		lhetime,
		picdirsize,
		pc1status,
		pc2status,
		pc1TotalEvents,
		pc2TotalEvents,
		totalEvents,
		pingPiCam1,
		pingPiCam2,
		handlepingPiCam1Click,
		handlepingPiCam2Click
	});

	$$self.$inject_state = $$props => {
		if ("pc2LastMovingDate" in $$props) $$invalidate(0, pc2LastMovingDate = $$props.pc2LastMovingDate);
		if ("pc2LastMovingTime" in $$props) $$invalidate(1, pc2LastMovingTime = $$props.pc2LastMovingTime);
		if ("pc2LastStillDate" in $$props) $$invalidate(2, pc2LastStillDate = $$props.pc2LastStillDate);
		if ("pc2LastStillTime" in $$props) $$invalidate(3, pc2LastStillTime = $$props.pc2LastStillTime);
		if ("pc1LastMovingDate" in $$props) $$invalidate(4, pc1LastMovingDate = $$props.pc1LastMovingDate);
		if ("pc1LastMovingTime" in $$props) $$invalidate(5, pc1LastMovingTime = $$props.pc1LastMovingTime);
		if ("pc1LastStillDate" in $$props) $$invalidate(6, pc1LastStillDate = $$props.pc1LastStillDate);
		if ("pc1LastStillTime" in $$props) $$invalidate(7, pc1LastStillTime = $$props.pc1LastStillTime);
		if ("lhedate" in $$props) $$invalidate(8, lhedate = $$props.lhedate);
		if ("lhetime" in $$props) $$invalidate(15, lhetime = $$props.lhetime);
		if ("picdirsize" in $$props) $$invalidate(9, picdirsize = $$props.picdirsize);
		if ("pc1status" in $$props) $$invalidate(10, pc1status = $$props.pc1status);
		if ("pc2status" in $$props) $$invalidate(11, pc2status = $$props.pc2status);
		if ("pc1TotalEvents" in $$props) $$invalidate(12, pc1TotalEvents = $$props.pc1TotalEvents);
		if ("pc2TotalEvents" in $$props) $$invalidate(13, pc2TotalEvents = $$props.pc2TotalEvents);
		if ("totalEvents" in $$props) $$invalidate(14, totalEvents = $$props.totalEvents);
		if ("handlepingPiCam1Click" in $$props) $$invalidate(16, handlepingPiCam1Click = $$props.handlepingPiCam1Click);
		if ("handlepingPiCam2Click" in $$props) $$invalidate(17, handlepingPiCam2Click = $$props.handlepingPiCam2Click);
	};

	if ($$props && "$$inject" in $$props) {
		$$self.$inject_state($$props.$$inject);
	}

	return [
		pc2LastMovingDate,
		pc2LastMovingTime,
		pc2LastStillDate,
		pc2LastStillTime,
		pc1LastMovingDate,
		pc1LastMovingTime,
		pc1LastStillDate,
		pc1LastStillTime,
		lhedate,
		picdirsize,
		pc1status,
		pc2status,
		pc1TotalEvents,
		pc2TotalEvents,
		totalEvents,
		lhetime,
		handlepingPiCam1Click,
		handlepingPiCam2Click
	];
}

class Routes extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], {});

		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterComponent", {
			component: this,
			tagName: "Routes",
			options,
			id: create_fragment.name
		});
	}
}

/* harmony default export */ __webpack_exports__["default"] = (Routes);

/***/ })

}]);
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vLi9zcmMvcm91dGVzL2luZGV4LnN2ZWx0ZSJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7Ozs7Ozs7Ozs7Ozs7OztBQUNrQzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7MkZBa0ZtQixHQUFpQjs7MkZBQ25CLEdBQWlCOzs7OzBGQUdmLEdBQWdCOzswRkFDbEIsR0FBZ0I7Ozs7bUZBR2hCLEdBQVM7Ozs7NEZBR04sR0FBaUI7OzRGQUNuQixHQUFpQjs7OzsyRkFHZixHQUFnQjs7MkZBQ2xCLEdBQWdCOzs7O29GQUdmLEdBQVM7Ozs7a0ZBR1IsR0FBTzs7a0ZBQ1YsR0FBTzs7Ozt5RkFHSixHQUFjOzs7O3lGQUlkLEdBQWM7Ozs7c0ZBSWQsR0FBVzs7OztxRkFJWixHQUFVOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs4R0F0Q1YsR0FBaUI7Ozs7Ozs7Ozs7Ozs7Ozs7OEdBQ25CLEdBQWlCOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs2R0FHZixHQUFnQjs7Ozs7Ozs7Ozs7Ozs7Ozs2R0FDbEIsR0FBZ0I7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O3NHQUdoQixHQUFTOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztnSEFHTixHQUFpQjs7Ozs7Ozs7Ozs7Ozs7OztnSEFDbkIsR0FBaUI7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OytHQUdmLEdBQWdCOzs7Ozs7Ozs7Ozs7Ozs7OytHQUNsQixHQUFnQjs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7d0dBR2YsR0FBUzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7c0dBR1IsR0FBTzs7Ozs7Ozs7Ozs7Ozs7OztzR0FDVixHQUFPOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs2R0FHSixHQUFjOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs2R0FJZCxHQUFjOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzswR0FJZCxHQUFXOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozt5R0FJWixHQUFVOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7a0hBL0JKLEdBQXFCO21IQVdwQixHQUFxQjs7Ozs7Ozt3SUFsQjVCLEdBQWlCO3dJQUNuQixHQUFpQjtzSUFHZixHQUFnQjt1SUFDbEIsR0FBZ0I7MEhBR2hCLEdBQVM7d0lBR04sR0FBaUI7d0lBQ25CLEdBQWlCO3NJQUdmLEdBQWdCO3NJQUNsQixHQUFnQjsySEFHZixHQUFTO3NIQUdSLEdBQU87cUlBSVAsR0FBYztxSUFJZCxHQUFjO2dJQUlkLEdBQVc7NEhBSVosR0FBVTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7S0F2SDFELGlCQUFpQixHQUFHLEVBQUU7S0FDdEIsaUJBQWlCLEdBQUcsRUFBRTtLQUN0QixnQkFBZ0IsR0FBRyxFQUFFO0tBQ3JCLGdCQUFnQixHQUFHLEVBQUU7S0FDckIsaUJBQWlCLEdBQUcsRUFBRTtLQUN0QixpQkFBaUIsR0FBRyxFQUFFO0tBQ3RCLGdCQUFnQixHQUFHLEVBQUU7S0FDckIsZ0JBQWdCLEdBQUcsRUFBRTtLQUNyQixPQUFPLEdBQUcsRUFBRTtLQUNaLE9BQU8sR0FBRyxFQUFFO0tBQ1osVUFBVSxHQUFHLEVBQUU7S0FDZixTQUFTLEdBQUcsRUFBRTtLQUNkLFNBQVMsR0FBRyxFQUFFO0tBRWQsY0FBYyxHQUFHLEVBQUU7S0FDbkIsY0FBYyxHQUFHLEVBQUU7S0FDbkIsV0FBVyxHQUFHLEVBQUU7O0NBQ3BCLHNEQUFPO1FBQ0EsS0FBSyxxQ0FBb0MsSUFBSSxFQUFFLE1BQU0sRUFBRSxNQUFNLEVBQUUsS0FBSyxJQUN6RSxJQUFJLENBQUMsQ0FBQyxJQUFJLENBQUMsQ0FBQyxJQUFJLElBQ2hCLElBQUksQ0FBQyxJQUFJO0dBQ1QsT0FBTyxDQUFDLEdBQUcsQ0FBQyxJQUFJOztPQUNaLElBQUksQ0FBQyxNQUFNLEtBQUssWUFBWTtvQkFDL0IsT0FBTyxHQUFHLFlBQVk7O29CQUV0QixPQUFPLEdBQUcsSUFBSSxDQUFDLE1BQU07OzttQkFFdEIsVUFBVSxHQUFHLElBQUksQ0FBQyxVQUFVO29CQUM1QixjQUFjLEdBQUcsSUFBSSxDQUFDLGNBQWM7b0JBQ3BDLGNBQWMsR0FBRyxJQUFJLENBQUMsY0FBYztvQkFDcEMsV0FBVyxHQUFHLElBQUksQ0FBQyxXQUFXO21CQUM5QixpQkFBaUIsR0FBRyxJQUFJLENBQUMsUUFBUSxDQUFDLE1BQU07T0FDcEMsR0FBRyxHQUFHLElBQUksQ0FBQyxRQUFRLENBQUMsTUFBTSxFQUFFLEtBQUssQ0FBQyxHQUFHO21CQUN6QyxpQkFBaUIsR0FBRyxHQUFHLENBQUMsQ0FBQzttQkFDekIsZ0JBQWdCLEdBQUcsSUFBSSxDQUFDLFFBQVEsQ0FBQyxNQUFNO09BQ25DLEtBQUssR0FBRyxJQUFJLENBQUMsUUFBUSxDQUFDLE1BQU0sRUFBRSxLQUFLLENBQUMsR0FBRzttQkFDM0MsZ0JBQWdCLEdBQUcsS0FBSyxDQUFDLENBQUM7bUJBQzFCLGlCQUFpQixHQUFHLElBQUksQ0FBQyxRQUFRLENBQUMsTUFBTTtPQUNwQyxNQUFNLEdBQUcsSUFBSSxDQUFDLFFBQVEsQ0FBQyxNQUFNLEVBQUUsS0FBSyxDQUFDLEdBQUc7bUJBQzVDLGlCQUFpQixHQUFHLE1BQU0sQ0FBQyxDQUFDO21CQUM1QixnQkFBZ0IsR0FBRyxJQUFJLENBQUMsUUFBUSxDQUFDLE1BQU07T0FDbkMsS0FBSyxHQUFHLElBQUksQ0FBQyxRQUFRLENBQUMsTUFBTSxFQUFFLEtBQUssQ0FBQyxHQUFHO21CQUMzQyxnQkFBZ0IsR0FBRyxLQUFLLENBQUMsQ0FBQztLQUN4QixLQUFLLENBQUMsR0FBRyxJQUFJLE9BQU8sQ0FBQyxHQUFHLENBQUMsR0FBRzs7O2dCQUVqQixVQUFVO1FBQ2xCLEtBQUssdUNBQXNDLElBQUksRUFBRSxNQUFNLEVBQUUsTUFBTSxFQUFFLEtBQUssSUFDM0UsSUFBSSxDQUFDLENBQUMsSUFBSSxDQUFDLENBQUMsSUFBSSxJQUNoQixJQUFJLENBQUMsSUFBSTtvQkFDVCxTQUFTLEdBQUcsSUFBSSxDQUFDLEtBQUs7S0FDcEIsS0FBSyxDQUFDLEdBQUcsSUFBSSxPQUFPLENBQUMsR0FBRyxDQUFDLEdBQUc7OztnQkFHakIsVUFBVTtRQUNsQixLQUFLLHVDQUFzQyxJQUFJLEVBQUUsTUFBTSxFQUFFLE1BQU0sRUFBRSxLQUFLLElBQzNFLElBQUksQ0FBQyxDQUFDLElBQUksQ0FBQyxDQUFDLElBQUksSUFDaEIsSUFBSSxDQUFDLElBQUk7b0JBQ1QsU0FBUyxHQUFHLElBQUksQ0FBQyxLQUFLO0tBQ3BCLEtBQUssQ0FBQyxHQUFHLElBQUksT0FBTyxDQUFDLEdBQUcsQ0FBQyxHQUFHOzs7S0FJNUIscUJBQXFCO01BQ3BCLE9BQU8sR0FBRyxVQUFVLEdBQUcsS0FBSyxDQUFDLEdBQUcsSUFBSSxPQUFPLENBQUMsR0FBRyxDQUFDLEdBQUc7OztLQUdwRCxxQkFBcUI7TUFDcEIsT0FBTyxHQUFHLFVBQVUsR0FBRyxLQUFLLENBQUMsR0FBRyxJQUFJLE9BQU8sQ0FBQyxHQUFHLENBQUMsR0FBRyIsImZpbGUiOiJiZmJiMDAwYTk4ZGZhMWVjY2IyNC9pbmRleC5pbmRleC5qcyIsInNvdXJjZXNDb250ZW50IjpbIjxzY3JpcHQ+XG5cdGltcG9ydCB7IG9uTW91bnQgfSBmcm9tICdzdmVsdGUnO1xuXHRsZXQgcGMyTGFzdE1vdmluZ0RhdGUgPSBcIlwiXG5cdGxldCBwYzJMYXN0TW92aW5nVGltZSA9IFwiXCJcblx0bGV0IHBjMkxhc3RTdGlsbERhdGUgPSBcIlwiXG5cdGxldCBwYzJMYXN0U3RpbGxUaW1lID0gXCJcIlxuXHRsZXQgcGMxTGFzdE1vdmluZ0RhdGUgPSBcIlwiXG5cdGxldCBwYzFMYXN0TW92aW5nVGltZSA9IFwiXCJcblx0bGV0IHBjMUxhc3RTdGlsbERhdGUgPSBcIlwiXG5cdGxldCBwYzFMYXN0U3RpbGxUaW1lID0gXCJcIlxuXHRsZXQgbGhlZGF0ZSA9IFwiXCJcblx0bGV0IGxoZXRpbWUgPSBcIlwiXG5cdGxldCBwaWNkaXJzaXplID0gXCJcIlxuXHRsZXQgcGMxc3RhdHVzID0gXCJcIlxuXHRsZXQgcGMyc3RhdHVzID0gXCJcIlxuXG5cdGxldCBwYzFUb3RhbEV2ZW50cyA9IFwiXCJcblx0bGV0IHBjMlRvdGFsRXZlbnRzID0gXCJcIlxuXHRsZXQgdG90YWxFdmVudHMgPSBcIlwiXG5cdG9uTW91bnQoYXN5bmMgKCkgPT4ge1xuXHRcdGF3YWl0IGZldGNoKGBodHRwOi8vMTkyLjE2OC4wLjI2OjgwOTAvc3RhdHNgLCB7bW9kZTogXCJjb3JzXCIsIG1ldGhvZDogXCJHRVRcIn0pXG5cdFx0LnRoZW4ociA9PiByLmpzb24oKSlcblx0XHQudGhlbihkYXRhID0+IHtcblx0XHRcdGNvbnNvbGUubG9nKGRhdGEpXG5cdFx0XHRpZiAoZGF0YS5oZWFsdGggPT09IFwiTm9uZSBub3RlZFwiKSB7XG5cdFx0XHRcdGxoZWRhdGUgPSBcIk5vbmUgbm90ZWRcIlxuXHRcdFx0fSBlbHNlIHtcblx0XHRcdFx0bGhlZGF0ZSA9IGRhdGEuaGVhbHRoXG5cdFx0XHR9XHRcblx0XHRcdHBpY2RpcnNpemUgPSBkYXRhLnBpY0RpclNpemVcblx0XHRcdHBjMVRvdGFsRXZlbnRzID0gZGF0YS5waWNhbTFBbGxUb2RheVxuXHRcdFx0cGMyVG90YWxFdmVudHMgPSBkYXRhLnBpY2FtMkFsbFRvZGF5XG5cdFx0XHR0b3RhbEV2ZW50cyA9IGRhdGEudG90YWxFdmVudHNcblx0XHRcdHBjMUxhc3RNb3ZpbmdEYXRlID0gZGF0YS5waWNhbTFMTVtcIkRhdGVcIl1cblx0XHRcdGxldCBhY2UgPSBkYXRhLnBpY2FtMUxNW1wiVGltZVwiXS5zcGxpdChcIixcIilcblx0XHRcdHBjMUxhc3RNb3ZpbmdUaW1lID0gYWNlWzBdXG5cdFx0XHRwYzFMYXN0U3RpbGxEYXRlID0gZGF0YS5waWNhbTFMU1tcIkRhdGVcIl1cblx0XHRcdGxldCBraW5ncyA9IGRhdGEucGljYW0xTFNbXCJUaW1lXCJdLnNwbGl0KFwiLFwiKVxuXHRcdFx0cGMxTGFzdFN0aWxsVGltZSA9IGtpbmdzWzBdXG5cdFx0XHRwYzJMYXN0TW92aW5nRGF0ZSA9IGRhdGEucGljYW0yTE1bXCJEYXRlXCJdXG5cdFx0XHRsZXQgcXVlZW5zID0gZGF0YS5waWNhbTJMTVtcIlRpbWVcIl0uc3BsaXQoXCIsXCIpXG5cdFx0XHRwYzJMYXN0TW92aW5nVGltZSA9IHF1ZWVuc1swXVxuXHRcdFx0cGMyTGFzdFN0aWxsRGF0ZSA9IGRhdGEucGljYW0yTFNbXCJEYXRlXCJdXG5cdFx0XHRsZXQgamFja3MgPSBkYXRhLnBpY2FtMkxTW1wiVGltZVwiXS5zcGxpdChcIixcIilcblx0XHRcdHBjMkxhc3RTdGlsbFRpbWUgPSBqYWNrc1swXVxuXHRcdH0pLmNhdGNoKGVyciA9PiBjb25zb2xlLmxvZyhlcnIpKTtcblx0fSlcblx0YXN5bmMgZnVuY3Rpb24gcGluZ1BpQ2FtMSgpIHtcblx0XHRhd2FpdCBmZXRjaChgaHR0cDovLzE5Mi4xNjguMC4yNjo4MDkwL3BpbmdwYzFgLCB7bW9kZTogXCJjb3JzXCIsIG1ldGhvZDogXCJHRVRcIn0pXG5cdFx0LnRoZW4ociA9PiByLmpzb24oKSlcblx0XHQudGhlbihkYXRhID0+IHtcblx0XHRcdHBjMXN0YXR1cyA9IGRhdGFbXCJwYzFcIl1cblx0XHR9KS5jYXRjaChlcnIgPT4gY29uc29sZS5sb2coZXJyKSk7XG5cdH1cblxuXHRhc3luYyBmdW5jdGlvbiBwaW5nUGlDYW0yKCkge1xuXHRcdGF3YWl0IGZldGNoKGBodHRwOi8vMTkyLjE2OC4wLjI2OjgwOTAvcGluZ3BjMmAsIHttb2RlOiBcImNvcnNcIiwgbWV0aG9kOiBcIkdFVFwifSlcblx0XHQudGhlbihyID0+IHIuanNvbigpKVxuXHRcdC50aGVuKGRhdGEgPT4ge1xuXHRcdFx0cGMyc3RhdHVzID0gZGF0YVtcInBjMlwiXVxuXHRcdH0pLmNhdGNoKGVyciA9PiBjb25zb2xlLmxvZyhlcnIpKTtcblxuXHR9XG5cblx0bGV0IGhhbmRsZXBpbmdQaUNhbTFDbGljayA9ICgpID0+IHtcblx0XHRsZXQgcHJvbWlzZSA9IHBpbmdQaUNhbTEoKS5jYXRjaChlcnIgPT4gY29uc29sZS5sb2coZXJyKSk7XG5cdH1cblxuXHRsZXQgaGFuZGxlcGluZ1BpQ2FtMkNsaWNrID0gKCkgPT4ge1xuXHRcdGxldCBwcm9taXNlID0gcGluZ1BpQ2FtMigpLmNhdGNoKGVyciA9PiBjb25zb2xlLmxvZyhlcnIpKTtcblx0fVxuPC9zY3JpcHQ+XG5cbjxzdmVsdGU6aGVhZD5cblx0PHRpdGxlPlNlY0NhbXM8L3RpdGxlPlxuPC9zdmVsdGU6aGVhZD5cblxuPHN2ZyB2aWV3Qm94PVwiMCAtNSAzMDAgMjU1XCIgPlxuXHQ8dGV4dCB4PVwiMFwiIHk9XCIxOFwiIGZvbnQtc2l6ZT1cIjJlbVwiIGZpbGw9XCJibGFja1wiPlNlY0NhbXM8L3RleHQ+XG5cblx0PGxpbmUgeDE9XCI1MFwiIHkxPVwiMjVcIiB4Mj1cIjI2MFwiIHkyPVwiMjVcIiBzdHlsZT1cInN0cm9rZTpyZ2IoMjU1LDAsMCk7c3Ryb2tlLXdpZHRoOjJcIiAvPlxuXG5cdDx0ZXh0IHg9XCIwXCIgeT1cIjQ3XCIgZm9udC1zaXplPVwiMWVtXCIgZmlsbD1cImJsYWNrXCIgPlBDMSBNb3Rpb248L3RleHQ+XG5cdDx0ZXh0IHg9XCIxMzVcIiB5PVwiNDdcIiBmb250LXNpemU9XCIxZW1cIiBmaWxsPVwiYmxhY2tcIiA+e3BjMUxhc3RNb3ZpbmdEYXRlfTwvdGV4dD5cblx0PHRleHQgeD1cIjIzMFwiIHk9XCI0N1wiIGZvbnQtc2l6ZT1cIjFlbVwiIGZpbGw9XCJwaW5rXCI+e3BjMUxhc3RNb3ZpbmdUaW1lfTwvdGV4dD5cblxuXHQ8dGV4dCB4PVwiMFwiIHk9XCI2N1wiIGZvbnQtc2l6ZT1cIjFlbVwiIGZpbGw9XCJibGFja1wiPjEgTGFzdCBTdGlsbDwvdGV4dD5cblx0PHRleHQgeD1cIjEzNVwiIHk9XCI2N1wiIGZvbnQtc2l6ZT1cIjFlbVwiIGZpbGw9XCJibGFja1wiID57cGMxTGFzdFN0aWxsRGF0ZX08L3RleHQ+XG5cdDx0ZXh0IHg9XCIyMzBcIiB5PVwiNjdcIiBmb250LXNpemU9XCIxZW1cIiBmaWxsPVwiYmx1ZVwiPntwYzFMYXN0U3RpbGxUaW1lfTwvdGV4dD5cblxuXHQ8dGV4dCB4PVwiMFwiIHk9XCI4N1wiIGZvbnQtc2l6ZT1cIjFlbVwiIGZpbGw9XCJibGFja1wiIG9uOmNsaWNrPXtoYW5kbGVwaW5nUGlDYW0xQ2xpY2t9PjEgUGluZyBzdGF0dXM8L3RleHQ+XG5cdDx0ZXh0IHg9XCIxMzVcIiB5PVwiODdcIiBmb250LXNpemU9XCIxZW1cIiBmaWxsPVwiYmx1ZVwiPntwYzFzdGF0dXN9PC90ZXh0PlxuXG5cdDx0ZXh0IHg9XCIwXCIgeT1cIjEwN1wiIGZvbnQtc2l6ZT1cIjFlbVwiIGZpbGw9XCJibGFja1wiID4yIExhc3QgTW90aW9uPC90ZXh0PlxuXHQ8dGV4dCB4PVwiMTM1XCIgeT1cIjEwN1wiIGZvbnQtc2l6ZT1cIjFlbVwiIGZpbGw9XCJibGFja1wiID57cGMyTGFzdE1vdmluZ0RhdGV9PC90ZXh0PlxuXHQ8dGV4dCB4PVwiMjMwXCIgeT1cIjEwN1wiIGZvbnQtc2l6ZT1cIjFlbVwiIGZpbGw9XCJwaW5rXCI+e3BjMkxhc3RNb3ZpbmdUaW1lfTwvdGV4dD5cblxuXHQ8dGV4dCB4PVwiMFwiIHk9XCIxMjdcIiBmb250LXNpemU9XCIxZW1cIiBmaWxsPVwiYmxhY2tcIj4yIExhc3QgU3RpbGw8L3RleHQ+XG5cdDx0ZXh0IHg9XCIxMzVcIiB5PVwiMTI3XCIgZm9udC1zaXplPVwiMWVtXCIgZmlsbD1cImJsYWNrXCIgPntwYzJMYXN0U3RpbGxEYXRlfTwvdGV4dD5cblx0PHRleHQgeD1cIjIzMFwiIHk9XCIxMjdcIiBmb250LXNpemU9XCIxZW1cIiBmaWxsPVwiYmx1ZVwiPntwYzJMYXN0U3RpbGxUaW1lfTwvdGV4dD5cblxuXHQ8dGV4dCB4PVwiMFwiIHk9XCIxNDdcIiBmb250LXNpemU9XCIxZW1cIiBmaWxsPVwiYmxhY2tcIiBvbjpjbGljaz17aGFuZGxlcGluZ1BpQ2FtMkNsaWNrfT4yIFBpbmcgU3RhdHVzPC90ZXh0PlxuXHQ8dGV4dCB4PVwiMTM1XCIgeT1cIjE0N1wiIGZvbnQtc2l6ZT1cIjFlbVwiIGZpbGw9XCJibHVlXCIgPntwYzJzdGF0dXN9PC90ZXh0PlxuXG5cdDx0ZXh0IHg9XCIwXCIgeT1cIjE2N1wiIGZvbnQtc2l6ZT1cIjFlbVwiIGZpbGw9XCJibGFja1wiPkhlYWx0aCBDaGVjazwvdGV4dD5cblx0PHRleHQgeD1cIjEzNVwiIHk9XCIxNjdcIiBmb250LXNpemU9XCIxZW1cIiBmaWxsPVwiYmxhY2tcIiA+e2xoZWRhdGV9PC90ZXh0PlxuXHQ8dGV4dCB4PVwiMjMwXCIgeT1cIjE2N1wiIGZvbnQtc2l6ZT1cIjFlbVwiIGZpbGw9XCJyZWRcIj57bGhldGltZX08L3RleHQ+XG5cblx0PHRleHQgeD1cIjBcIiB5PVwiMTg3XCIgZm9udC1zaXplPVwiMWVtXCIgZmlsbD1cImJsYWNrXCI+UGlDYW0xIFRvdGFsPC90ZXh0PlxuXHQ8dGV4dCB4PVwiMTM1XCIgeT1cIjE4N1wiIGZvbnQtc2l6ZT1cIjFlbVwiIGZpbGw9XCJibGFja1wiID57cGMxVG90YWxFdmVudHN9PC90ZXh0PlxuXHQ8IS0tIDx0ZXh0IHg9XCIyMzBcIiB5PVwiMTY3XCIgZm9udC1zaXplPVwiMWVtXCIgZmlsbD1cInJlZFwiPntsaGV0aW1lfTwvdGV4dD4gLS0+XG5cblx0PHRleHQgeD1cIjBcIiB5PVwiMjA3XCIgZm9udC1zaXplPVwiMWVtXCIgZmlsbD1cImJsYWNrXCI+UGlDYW0yIFRvdGFsPC90ZXh0PlxuXHQ8dGV4dCB4PVwiMTM1XCIgeT1cIjIwN1wiIGZvbnQtc2l6ZT1cIjFlbVwiIGZpbGw9XCJibGFja1wiID57cGMyVG90YWxFdmVudHN9PC90ZXh0PlxuXHQ8IS0tIDx0ZXh0IHg9XCIyMzBcIiB5PVwiMTY3XCIgZm9udC1zaXplPVwiMWVtXCIgZmlsbD1cInJlZFwiPntsaGV0aW1lfTwvdGV4dD4gLS0+XG5cblx0PHRleHQgeD1cIjBcIiB5PVwiMjI3XCIgZm9udC1zaXplPVwiMWVtXCIgZmlsbD1cImJsYWNrXCI+VG90YWwgRXZlbnRzPC90ZXh0PlxuXHQ8dGV4dCB4PVwiMTM1XCIgeT1cIjIyN1wiIGZvbnQtc2l6ZT1cIjFlbVwiIGZpbGw9XCJibGFja1wiID57dG90YWxFdmVudHN9PC90ZXh0PlxuXHQ8IS0tIDx0ZXh0IHg9XCIyMzBcIiB5PVwiMTY3XCIgZm9udC1zaXplPVwiMWVtXCIgZmlsbD1cInJlZFwiPntsaGV0aW1lfTwvdGV4dD4gLS0+XG5cblx0PHRleHQgeD1cIjBcIiB5PVwiMjQ3XCIgZm9udC1zaXplPVwiMWVtXCIgZmlsbD1cImJsYWNrXCI+UGljIEZvbGRlciBTaXplPC90ZXh0PlxuXHQ8dGV4dCB4PVwiMTM1XCIgeT1cIjI0N1wiIGZvbnQtc2l6ZT1cIjFlbVwiIGZpbGw9XCJibGFja1wiPntwaWNkaXJzaXplfTwvdGV4dD5cblxuXG5cblx0U29ycnksIHlvdXIgYnJvd3NlciBkb2VzIG5vdCBzdXBwb3J0IGlubGluZSBTVkcuICBcbjwvc3ZnPlxuXG48c3R5bGU+XG5cbjwvc3R5bGU+Il0sInNvdXJjZVJvb3QiOiIifQ==